---
# tasks file for monsieurbiz.common

- name: Update the server
  apt: update_cache=true cache_valid_time={{ monsieurbiz_common_cache_valid_time }}
  when: monsieurbiz_common_update
  tags: [common, update]

- name: Upgrade the server packages
  apt: upgrade=yes
  when: monsieurbiz_common_upgrade
  tags: [common, update]

- name: Install some packages
  apt:
    name: '{{ monsieurbiz_common_packages }}'
    state: latest
  tags: [common]
